"""Add currency column to user_upload

Revision ID: f5c4aca6c453
Revises: 
Create Date: 2025-04-09 21:06:10.151098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f5c4aca6c453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_upload')
    with op.batch_alter_table('user_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_upload', schema=None) as batch_op:
        batch_op.drop_column('currency')

    op.create_table('data_upload',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=120), nullable=False),
    sa.Column('upload_date', sa.DATETIME(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('forecast', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
